/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EmailEntry = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'tone' : IDL.Text,
  'emailBody' : IDL.Text,
  'recipientName' : IDL.Text,
});
export const EmailSettings = IDL.Record({
  'defaultTone' : IDL.Text,
  'signOff' : IDL.Text,
  'fullName' : IDL.Text,
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'defaultPronouns' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'deleteEmail' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(EmailEntry)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(EmailSettings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasHistory' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [EmailEntry],
      [],
    ),
  'saveSettings' : IDL.Func([EmailSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EmailEntry = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'tone' : IDL.Text,
    'emailBody' : IDL.Text,
    'recipientName' : IDL.Text,
  });
  const EmailSettings = IDL.Record({
    'defaultTone' : IDL.Text,
    'signOff' : IDL.Text,
    'fullName' : IDL.Text,
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'defaultPronouns' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'deleteEmail' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(EmailEntry)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(EmailSettings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasHistory' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [EmailEntry],
        [],
      ),
    'saveSettings' : IDL.Func([EmailSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };